"""initial schema

Revision ID: bbdda67c4d93
Revises: 
Create Date: 2026-03-13 19:13:38.737177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdda67c4d93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brokerage_accounts_id'), table_name='brokerage_accounts')
    op.drop_table('brokerage_accounts')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_stocks_in_watchlist_id'), table_name='stocks_in_watchlist')
    op.drop_table('stocks_in_watchlist')
    op.drop_index(op.f('ix_sell_transactions_id'), table_name='sell_transactions')
    op.drop_table('sell_transactions')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('avatar_color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('owner_user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('sell_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), nullable=False),
    sa.Column('shares_sold', sa.FLOAT(), nullable=False),
    sa.Column('price_received', sa.FLOAT(), nullable=False),
    sa.Column('sell_date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sell_transactions_id'), 'sell_transactions', ['id'], unique=False)
    op.create_table('stocks_in_watchlist',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), nullable=False),
    sa.Column('buy_reasons', sa.TEXT(), nullable=True),
    sa.Column('sell_conditions', sa.TEXT(), nullable=True),
    sa.Column('buy_price', sa.FLOAT(), nullable=True),
    sa.Column('sell_price', sa.FLOAT(), nullable=True),
    sa.Column('stop_loss_pct', sa.FLOAT(), nullable=True),
    sa.Column('added_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_in_watchlist_id'), 'stocks_in_watchlist', ['id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('entry_price', sa.FLOAT(), nullable=False),
    sa.Column('entry_date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['brokerage_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_table('brokerage_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('broker_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokerage_accounts_id'), 'brokerage_accounts', ['id'], unique=False)
    # ### end Alembic commands ###
